---
Name: blogsearch
---

Blog:
  extensions:
    - BlogSearchBlogExtension

Blog_Controller:
  extensions:
    - EnableBlogSearchFormExtension

BlogPost_Controller:
  extensions:
    - EnableBlogSearchFormExtension
